flowchart LR

subgraph 0[".yarn"]
subgraph 1["releases"]
2["yarn-4.5.3.cjs"]
end
end
3["checkPortAvailability.js"]
4["net"]
5["server.js"]
subgraph 6["@controller"]
7["apiColumnsController"]
8["fetchEventTypes"]
1I["execEventType"]
1J["initialize"]
1K["listRegisteredRoutes"]
1L["restartServer"]
end
subgraph 9["@root"]
subgraph A["server"]
B["app"]
end
end
subgraph C["@routes"]
D["registerRoutes"]
end
F["db.js"]
subgraph G["server"]
subgraph H["utils"]
I["dbConfig.js"]
1M["dbUtils.js"]
1N["queryResolver.js"]
1O["softDelete.js"]
1P["timestamp.js"]
end
M["app.js"]
subgraph N["controller"]
O["Initialize.js"]
P["apiColumnsController.js"]
T["execEventType.js"]
Y["fetchEventTypes.js"]
Z["listRegisteredRoutes.js"]
10["queryResolver.js"]
11["restartServer.js"]
13["userLogin.js"]
end
subgraph 14["middleware"]
subgraph 15["api"]
16["apiClient.js"]
17["apiColumns.js"]
18["apiHandler.js"]
1B["callAPI.js"]
end
subgraph 1C["events"]
1D["eventLookup.js"]
1E["eventRoutes.js"]
end
end
subgraph 1F["routes"]
1G["index.js"]
1H["registerRoutes.js"]
end
end
J["depency-cruiser.config.js"]
K["log-and-restart.js"]
L["postcss.config.js"]
subgraph Q["@utils"]
R["dbUtils"]
X["queryResolver"]
end
S["fs"]
subgraph U["@middleware"]
subgraph V["events"]
W["eventRoutes"]
end
end
12["child_process"]
subgraph 19["@events"]
1A["eventLookup"]
end
1Q["tailwind.config.js"]
1R["temp.dependency-cruiser.js"]
3-->5
3-->4
5-->7
5-->8
5-->B
5-->D
5-->E
F-->I
I-->E
M-->E
O-->E
P-->R
P-->S
P-->E
T-->W
T-->R
T-->X
T-->E
Y-->S
Y-->E
Z-->E
10-->W
10-->R
10-->E
11-->12
13-->R
18-->1A
1D-->W
1G-->D
1G-->E
1H-->7
1H-->1I
1H-->8
1H-->1J
1H-->1K
1H-->1L
1H-->E
1N-->E
