CREATE OR REPLACE FUNCTION deployment.f_table_ddl(p_schema text, p_table text)
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_oid  oid;
    v_seq  text;
    v_own  text;
    v_cols text;
    v_addcols text;
    v_cons text;
    v_idx  text;
BEGIN
    SELECT c.oid INTO v_oid
      FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = p_schema AND c.relname = p_table AND c.relkind = 'r';

    IF v_oid IS NULL THEN
        RAISE EXCEPTION 'f_table_ddl: no such table %.%', p_schema, p_table;
    END IF;

    -- Sequences this table depends on. NOT in vw_manifest, so if they are not
    -- emitted here a nextval() default fails on a bare target.
    WITH seqs AS (
        SELECT s.oid, sn.nspname, s.relname
          FROM pg_attrdef ad
          JOIN pg_depend d ON d.objid = ad.oid AND d.classid = 'pg_attrdef'::regclass
          JOIN pg_class s ON s.oid = d.refobjid AND s.relkind = 'S'
          JOIN pg_namespace sn ON sn.oid = s.relnamespace
         WHERE ad.adrelid = v_oid
        UNION
        SELECT s.oid, sn.nspname, s.relname
          FROM pg_depend d
          JOIN pg_class s ON s.oid = d.objid AND s.relkind = 'S'
          JOIN pg_namespace sn ON sn.oid = s.relnamespace
         WHERE d.refobjid = v_oid AND d.deptype = 'a'
    )
    SELECT string_agg(format('CREATE SEQUENCE IF NOT EXISTS %I.%I;', nspname, relname), E'\n')
      INTO v_seq FROM seqs;

    SELECT string_agg(
             format('    %I %s%s%s%s',
                    a.attname,
                    format_type(a.atttypid, a.atttypmod),
                    CASE a.attidentity
                      WHEN 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
                      WHEN 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
                      ELSE '' END,
                    CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END,
                    CASE WHEN ad.adbin IS NOT NULL AND a.attidentity = ''
                         THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
                         ELSE '' END),
             E',\n' ORDER BY a.attnum)
      INTO v_cols
      FROM pg_attribute a
      LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
     WHERE a.attrelid = v_oid AND a.attnum > 0 AND NOT a.attisdropped;

    -- Reconcile columns on a target where the table already exists: CREATE
    -- TABLE IF NOT EXISTS above is a no-op there, so any new column must be
    -- added explicitly. ADD COLUMN IF NOT EXISTS is natively idempotent, so
    -- this is harmless (a true no-op) on a target where CREATE TABLE just
    -- created the column instead.
    SELECT string_agg(
             format(E'\nALTER TABLE %I.%I ADD COLUMN IF NOT EXISTS %I %s%s%s%s;',
                    p_schema, p_table,
                    a.attname,
                    format_type(a.atttypid, a.atttypmod),
                    CASE a.attidentity
                      WHEN 'a' THEN ' GENERATED ALWAYS AS IDENTITY'
                      WHEN 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY'
                      ELSE '' END,
                    CASE WHEN ad.adbin IS NOT NULL AND a.attidentity = ''
                         THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
                         ELSE '' END,
                    CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END),
             '' ORDER BY a.attnum)
      INTO v_addcols
      FROM pg_attribute a
      LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
     WHERE a.attrelid = v_oid AND a.attnum > 0 AND NOT a.attisdropped;

    -- Re-establish sequence ownership so DROP TABLE still cascades correctly.
    -- Idempotent already: re-asserting the same ownership is a no-op, no error.
    SELECT string_agg(
             format(E'\nALTER SEQUENCE %I.%I OWNED BY %I.%I.%I;',
                    sn.nspname, s.relname, p_schema, p_table, a.attname), '')
      INTO v_own
      FROM pg_depend d
      JOIN pg_class s ON s.oid = d.objid AND s.relkind = 'S'
      JOIN pg_namespace sn ON sn.oid = s.relnamespace
      JOIN pg_attribute a ON a.attrelid = d.refobjid AND a.attnum = d.refobjsubid
     WHERE d.refobjid = v_oid AND d.deptype = 'a';

    -- Postgres has no native ADD CONSTRAINT IF NOT EXISTS. Guard by name via
    -- pg_constraint instead of catching an exception, so a genuinely different
    -- error (bad definition, etc.) still surfaces instead of being swallowed.
    SELECT string_agg(
             format(E'\nDO $do$\nBEGIN\n  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = %L AND conrelid = %L::regclass) THEN\n    ALTER TABLE %I.%I ADD CONSTRAINT %I %s;\n  END IF;\nEND\n$do$;',
                    con.conname, p_schema || '.' || p_table, p_schema, p_table, con.conname, pg_get_constraintdef(con.oid)),
             '' ORDER BY CASE con.contype WHEN 'p' THEN 1 WHEN 'u' THEN 2
                                          WHEN 'c' THEN 3 ELSE 4 END, con.conname)
      INTO v_cons
      FROM pg_constraint con
     WHERE con.conrelid = v_oid;

    -- Postgres DOES support CREATE INDEX IF NOT EXISTS natively; pg_get_indexdef
    -- just doesn't emit it, so inject it.
    SELECT string_agg(
             E'\n' || regexp_replace(pg_get_indexdef(i.indexrelid), '^(CREATE (UNIQUE )?INDEX )', '\1IF NOT EXISTS ') || ';',
             '')
      INTO v_idx
      FROM pg_index i
     WHERE i.indrelid = v_oid
       AND NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conindid = i.indexrelid);

    RETURN coalesce(v_seq || E'\n', '')
           || format(E'CREATE TABLE IF NOT EXISTS %I.%I (\n%s\n);', p_schema, p_table, v_cols)
           || coalesce(v_addcols, '') || coalesce(v_own, '') || coalesce(v_cons, '') || coalesce(v_idx, '');
END
$function$
;

